[servers]
loadbalancer ansible_host=192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/loadbalancer/vmware_desktop/private_key
webserver1 ansible_host=192.168.56.12 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/webserver1/vmware_desktop/private_key
webserver2 ansible_host=192.168.56.13 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/webserver2/vmware_desktop/private_key
appserver ansible_host=192.168.56.14 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/appserver/vmware_desktop/private_key
backup ansible_host=192.168.56.15 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/backup/vmware_desktop/private_key
monitoring ansible_host=192.168.56.17 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/monitoring/vmware_desktop/private_key

[servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
