input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] == "vitals-backend-app" {
    json {
      source => "message"
    }
  }

  if "_grokparsefailure" in [tags] {
    mutate {
      add_tag => [ "unparsed" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
}
